mizugi/config/routes.rb
Rails.application.routes.draw do
  get 'categories/index'
  devise_scope :user do
    get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
    get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
  end
  devise_for :users, path: 'users', controllers: {
    sessions: 'users/sessions',
    confirmations: 'users/confirmations'
  }
  get 'products/index'
  get 'products/update_price'
  resources :products
  root to: 'products#index'
  
  # resources :carts
  get '/carts', to: 'carts#index'
  post "carts", to: "carts#update"
  delete "carts", to: "carts#destroy"
  
  resources :categories
  get '/category', to: 'categories#index'
  get '/checkout', to: 'payments#checkout'
  
  resources :ratings, only: [:create]
  resources :orders
  
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :charges, only: %i(create)
  
  post "comments", to: "comments#create"
end

mizugi/app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :product_feature
  mount_uploaders :images, ImageUploader
  serialize :images, JSON
  has_many :ratings
  NUM_OF_PRODUCTS_HOMEPAGE = 8

  attr_accessor :delete_images
  after_validation do
    uploaders = images.delete_if do |uploader|
      if Array(delete_images).include?(uploader.file.identifier)
        uploader.remove!
        true
      end
    end
    write_attribute(:images, uploaders.map { |uploader| uploader.file.identifier })
  end
  
  scope :latest, -> { order(created_at: :desc).limit(NUM_OF_PRODUCTS_HOMEPAGE) }

  def images=(files)
    appended = files.map do |file|
      uploader = _mounter(:images).blank_uploader
      uploader.cache! file
      uploader
    end
    super(images + appended)
  end
  
  def get_average_rating
    return self.ratings.average(:rate)
  end
  
  class << self
    def male_product_colors(product)
      product.product_feature.for_male.uniq{|x| x.color}.pluck(:color)
    end
    
    def female_product_colors(product)
      product.product_feature.for_female.uniq{|x| x.color}.pluck(:color)
    end
    
    def male_product_sizes(product)
      product.product_feature.for_male.uniq{|x| x.size}.pluck(:size)
    end
    
    def female_product_sizes(product)
      product.product_feature.for_female.uniq{|x| x.size}.pluck(:size)
    end
    
    def default_price(product)
      product.product_feature.for_male.first.price + product.product_feature.for_female.first.price 
    end
  end
end

mizugi/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    set_categories_data
    set_products_data
  end
  
  def show
    @product = Product.includes(:product_feature, :category).find(params[:id])
    @selected_male_product = @product.product_feature.for_male.first
    @selected_female_product = @product.product_feature.for_female.first
    @male_product_colors = Product.male_product_colors(@product)
    @female_product_colors = Product.female_product_colors(@product)
    @male_product_sizes = Product.male_product_sizes(@product)
    @female_product_sizes = Product.female_product_sizes(@product)
    @all_comments = Comment.includes(:user).where(product_id: @product.id)
  end
  
  def update_price
    @product = Product.includes(:product_feature, :category).find(params[:id])
    @selected_male_product = @product.product_feature.for_male.where(size: params[:male_size], color: params[:male_color]).first
    @selected_female_product = @product.product_feature.for_female.where(size: params[:female_size], color: params[:female_color]).first
    
    render json: {
      selected_male_product: @selected_male_product,
      selected_female_product: @selected_female_product
    }
  end
  
  private
  
  def set_categories_data
    @categories = Category.all
  end
  
  def set_products_data
    @products = Product.limit(8)
    @latest_products = Product.latest
  end
end

mizugi/app/helpers/products_helper.rb
module ProductsHelper
end

mizugi/app/views/products/index.html.slim
/! start banner Area
section.banner-area
  .container
    .row.fullscreen.align-items-center.justify-content-start
      .col-lg-12
        .active-banner-slider.owl-carousel
          /! single-slide
          .row.single-slide.align-items-center.d-flex
            .col-lg-5.col-md-6
              .banner-content
                h1
                  | NEW COLLECTION
                h4
                  | Welcome to Mizugi, your shopping destination for fashion online. We offer fashion and quality at the best price in a more sustainable way.
            .col-lg-7
              .banner-img
                = image_tag("banner/banner-img.png", alt: "", class: "img-fluid")
          /! single-slide
          .row.single-slide
            .col-lg-5
              .banner-content
                h1
                  | NEW COLLECTION
                h4
                  | Mizugi provides the latest fashions at great prices for couples.
                  | We delivers innovative products, experiences and services to inspire athletes.
            .col-lg-7
              .banner-img
                = image_tag("banner/banner-img.png", alt: "", class: "img-fluid")
/! End banner Area
/! start features Area
section.features-area.section_gap
  .container
    .row.features-inner
      /! single features
      .col-lg-3.col-md-6.col-sm-6
        .single-features
          .f-icon
            = image_tag("features/f-icon1.png", alt: "")
          h6 Free Delivery
          p Free Shipping on all order
      /! single features
      .col-lg-3.col-md-6.col-sm-6
        .single-features
          .f-icon
            = image_tag("features/f-icon2.png", alt: "")
          h6 Return Policy
          p Free Shipping on all order
      /! single features
      .col-lg-3.col-md-6.col-sm-6
        .single-features
          .f-icon
            = image_tag("features/f-icon3.png", alt: "")
          h6 24/7 Support
          p Free Shipping on all order
      /! single features
      .col-lg-3.col-md-6.col-sm-6
        .single-features
          .f-icon
            = image_tag("features/f-icon4.png", alt: "")
          h6 Secure Payment
          p Free Shipping on all order
/! end features Area
/! Start category Area
section.category-area
  .container
    .row.justify-content-center
      .col-lg-8.col-md-12
        .row
          .col-lg-8.col-md-8
            .single-deal
              .overlay
              = image_tag("category/c1.jpg", alt: "", class: "img-fluid w-100")
              a.img-pop-up href="/categories/2" 
              .deal-details
                h6.deal-title Sneaker for Sports
          .col-lg-4.col-md-4
            .single-deal
              .overlay
              = image_tag("category/c2.jpg", alt: "", class: "img-fluid w-100")
              a.img-pop-up href="/categories/2" target="_blank" 
              .deal-details
                h6.deal-title Sneaker for Sports
          .col-lg-4.col-md-4
            .single-deal
              .overlay
              = image_tag("category/c3.jpg", alt: "", class: "img-fluid w-100")
              a.img-pop-up href="/categories/1" target="_blank" 
              .deal-details
                h6.deal-title Clothes for Couple
          .col-lg-8.col-md-8
            .single-deal
              .overlay
              = image_tag("category/c4.jpg", alt: "", class: "img-fluid w-100")
              a.img-pop-up href="/categories/1" target="_blank" 
              .deal-details
                h6.deal-title Clothes for Couple
      .col-lg-4.col-md-6
        .single-deal
          .overlay
          = image_tag("category/c5.jpg", alt: "", class: "img-fluid w-100")
          a.img-pop-up href="/categories/3" target="_blank" 
          .deal-details
            h6.deal-title Gym Equipments
/! End category Area
/! start product Area
section.owl-carousel.active-product-area.section_gap
  /! single product slide
  .single-product-slider
    .container
      .row.justify-content-center
        .col-lg-6.text-center
          .section-title
            h1 Latest Products
      .row
        - @latest_products.each do |latest_product|
          /! single product|
          .col-lg-3.col-md-6
            .single-product
              a href="/products/#{latest_product.id}"
                = image_tag("#{latest_product.images[0]}", alt: "", class: "img-fluid")
              .product-details
                h6
                  = latest_product.name
                .price
                  h6 = "$ #{latest_product.product_feature[0].price}"
                .prd-bottom
                  a.social-info href="" 
                    span.ti-bag
                    p.hover-text Add to cart
                  a.social-info href="/products/#{latest_product.id}" 
                    span.lnr.lnr-move
                    p.hover-text View more
      .row style='float: right'
        a href="/categories"
          h5
            i style='color: #ffba00' Show more >>
  /! single product slide
  .single-product-slider
    .container
      .row.justify-content-center
        .col-lg-6.text-center
          .section-title
            h1 All Products
            p
      .row
        - @products.each do |product|
          /! single product
          .col-lg-3.col-md-6
            .single-product
              a href="/products/#{product.id}"
                = image_tag("#{product.images[0]}", alt: "", class: "img-fluid")
              .product-details
                h6
                  = product.name
                .price
                  h6 = "#{product.product_feature[0].price} vnd"
                .prd-bottom
                  a.social-info href="" 
                    span.ti-bag
                    p.hover-text Add to bag
                  a.social-info href="/products/#{product.id}" 
                    span.lnr.lnr-move
                    p.hover-text View more
      
      .row style='float: right'
        a href="/categories"
          h5
            i style='color: #ffba00' Show more >>
/! end product Area
/! Start brand Area
section.features-area.section_gap style='padding-top: 0px !important'
  .container
    .row.features-inner
      /! single features
      .col-lg-4.col-md-4.col-sm-4
        .single-features
          a.social-info href="/categories/1"
            .f-icon
              = image_tag("elements/clothes.png", alt: "", class: "brand-icon")
            h6 Clothes
      /! single features
      .col-lg-4.col-md-4.col-sm-4
        .single-features
          a.social-info href="/categories/2"
            .f-icon
              = image_tag("elements/shoes.png", alt: "", class: "brand-icon")
            h6 Shoes
      /! single features
      .col-lg-4.col-md-4.col-sm-4
        .single-features
          a.social-info href="/categories/3"
            .f-icon
              = image_tag("elements/equipments.png", alt: "", class: "brand-icon")
            h6 Equipments
/! End brand Area

mizugi/app/views/products/show.html.slim
/! ================Single Product Area =================
#product-id data-product_id=@product.id
.product_image_area
  .container
    .row.s_product_inner
      .col-lg-6
        - if @product.images.length > 1
          .s_Product_carousel
            - @product.images.each do |image|
              .single-prd-item
                = image_tag("#{image}", alt: "", class: "img-fluid")
        - else
          .single-prd-item
            = image_tag("#{@product.images[0]}", alt: "", class: "img-fluid")
          img src="http://www.dallasshirtprinting.com/wp-content/uploads/2017/06/dallas-shirt-printing-logo-retina.png" class="custom-logo"
      .col-lg-5.offset-lg-1
        .s_product_text
          h3 = @product.name
          h2#product-price = "$#{@selected_male_product.price + @selected_female_product.price}"
          ul.list
            li
              a.active href="#" 
                span Category
                = @product.category.name
            li
              a href="#" 
                span Availibility
                | In Stock
          - if @product.customizable
            .card_area.d-flex.align-items-center style='margin-top: 30px;'
              button.primary-btn data-toggle="modal" data-target="#customLogoModal"
                = 'Upload custom logo'
          p
            = @product.description
          .product_count
            table.product-description-table
              tr
                th
                th Product 1
                th Product 2
              tr
                td style='padding-right: 30px;' Gender
                td
                  select.gender-select-1
                    option = "Male"
                    option = "Female"
                td style='padding-right: 30px;'
                  select.gender-select-2
                    option = "Female"
                    option = "Male"
              tr
                td style='padding-right: 30px;' Color
                td
                  select.color-select-male
                    - @male_product_colors.each do |color|
                      option
                        = color
                td style='padding-right: 30px;'
                  select.color-select-female
                    - @female_product_colors.each do |color|
                      option
                        = color
              tr
                td style='padding-right: 30px;' Size
                td style='padding-right: 30px;'
                  select.size-select-male
                    - @male_product_sizes.each do |size|
                      option name="male-size"
                        = size
                td style='padding-right: 30px;'
                  select.size-select-female
                    - @female_product_sizes.each do |size|
                      option name="female-size"
                        = size
            = form_for :cart, :url => carts_path do |f|
              = f.label :quantity
              = f.number_field :quantity, value: 1, name: "product_feature_qty", style: "padding-right: 30px;"
              = f.hidden_field :male_product_id, value: @selected_male_product.id, name: "male_product_id"
              = f.hidden_field :female_product_id, value: @selected_female_product.id, name: "female_product_id"
              = f.hidden_field :btn_type, name: "btn_type", value: "add"
              .card_area.d-flex.align-items-center style='margin-top: 30px;'
                = f.submit 'Add to Cart', class: "primary-btn"
/! ================End Single Product Area =================
/! ================Product Description Area =================
section.product_description_area
  .container
    ul#myTab.nav.nav-tabs role="tablist" 
      li.nav-item
        a#home-tab.nav-link aria-controls="home" aria-selected="true" data-toggle="tab" href="#home" role="tab"  Description
      li.nav-item
        a#contact-tab.nav-link aria-controls="review" aria-selected="false" data-toggle="tab" href="#review" role="tab"  Comments
    #myTabContent.tab-content
      #home.tab-pane.fade aria-labelledby="home-tab" role="tabpanel" 
        p
          | Beryl Cook is one of Britain’s most talented and amusing artists .Beryl’s pictures feature women of all shapes
          | and sizes enjoying themselves .Born between the two world wars, Beryl Cook eventually left Kendrick School in
          | Reading at the age of 15, where she went to secretarial school and then into an insurance office. After moving to
          | London and then Hampton, she eventually married her next door neighbour from Reading, John Cook. He was an
          | officer in the Merchant Navy and after he left the sea in 1956, they bought a pub for a year before John took a
          | job in Southern Rhodesia with a motor company. Beryl bought their young son a box of watercolours, and when
          | showing him how to use it, she decided that she herself quite enjoyed painting. John subsequently bought her a
          | child’s painting set for her birthday and it was with this that she produced her first significant work, a
          | half-length portrait of a dark-skinned lady with a vacant expression and large drooping breasts. It was aptly
          | named ‘Hangover’ by Beryl’s husband and
        p
          | It is often frustrating to attempt to plan meals that are designed for one. Despite this fact, we are seeing
          | more and more recipe books and Internet websites that are dedicated to the act of cooking for one. Divorce and
          | the death of spouses or grown children leaving for college are all reasons that someone accustomed to cooking for
          | more than one would suddenly need to learn how to adjust all the cooking practices utilized before into a
          | streamlined plan of cooking that is more efficient for one person creating less
      #review.tab-pane.fade.show.active aria-labelledby="review-tab" role="tabpanel" 
        .row
          .col-lg-6
            .row.total_rate
              .col-6
                .box_total
                  h5 Overall
                  h4 = @product.get_average_rating ? @product.get_average_rating : "0.0"
                  h6 (03 Reviews)
              .col-6
                .rating_list
                  ul.list
                    li
                      a href="#" 
                        i.fa.fa-star
                        i.fa.fa-star
                        i.fa.fa-star
                        i.fa.fa-star
                        i.fa.fa-star
                        | &nbsp;
                        = "(#{@product.ratings.where(rate: 5).count})"
                    li
                      a href="#" 
                        i.fa.fa-star
                        i.fa.fa-star
                        i.fa.fa-star
                        i.fa.fa-star
                        i.fa.fa-star.text-secondary
                        | &nbsp;
                        = "(#{@product.ratings.where(rate: 4).count})"
                    li
                      a href="#" 
                        i.fa.fa-star
                        i.fa.fa-star
                        i.fa.fa-star
                        i.fa.fa-star.text-secondary
                        i.fa.fa-star.text-secondary
                        | &nbsp;
                        = "(#{@product.ratings.where(rate: 3).count})"
                    li
                      a href="#" 
                        i.fa.fa-star
                        i.fa.fa-star
                        i.fa.fa-star.text-secondary
                        i.fa.fa-star.text-secondary
                        i.fa.fa-star.text-secondary
                        | &nbsp;
                        = "(#{@product.ratings.where(rate: 2).count})"
                    li
                      a href="#" 
                        i.fa.fa-star
                        i.fa.fa-star.text-secondary
                        i.fa.fa-star.text-secondary
                        i.fa.fa-star.text-secondary
                        i.fa.fa-star.text-secondary
                        | &nbsp;
                        = "(#{@product.ratings.where(rate: 1).count})"
            .review_list
              - @all_comments.each do |comment|
                .review_item
                  .media
                    .d-flex
                      = image_tag("product/review-1.png", alt: "")
                    .media-body
                      h4 = comment.user.email
                      p = comment.content

          .col-lg-6
            .row
              .col-sm-12
                h4 Rate this product
                - if user_signed_in?
                  #rate-score data-rate=current_user.ratings.where(product_id: @product.id).first&.rate 
                  .rate
                    input#star5.star-rating name="rate" type="radio" value="5" /
                    label for="star5" title="text"  5 stars
                    input#star4.star-rating name="rate" type="radio" value="4" /
                    label for="star4" title="text"  4 stars
                    input#star3.star-rating name="rate" type="radio" value="3" /
                    label for="star3" title="text"  3 stars
                    input#star2.star-rating name="rate" type="radio" value="2" /
                    label for="star2" title="text"  2 stars
                    input#star1.star-rating name="rate" type="radio" value="1" /
                    label for="star1" title="text"  1 star
            .review_box
              - if user_signed_in?
                h4 Add a Comment
                = form_for :comments, :url => comments_path do |f|
                  div#contactForm.row.contact_form
                    .col-md-12
                      .form-group
                        = f.hidden_field :user_id, value: current_user.id
                        = f.hidden_field :product_id, value: @product.id
                        = f.text_area :content, id: "message", class: "form-control", placeholder: "Review", rows: "1"
                    .col-md-12.text-right
                      button.primary-btn type="submit" value="submit"  Submit Now
/! ================End Product Description Area =================

div class="modal fade" id="customLogoModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true"
  div.modal-dialog role="document"
    div.modal-content
      div.modal-header
        h5.modal-title Upload your design
        button type="button" class="close" data-dismiss="modal" aria-label="Close"
          span aria-hidden="true" &times;
      div.modal-body
        input type="file" onchange="readURL(this);"
        br
        img id="preview" src="#" alt="your image" style="width: 100%; display: none"
      div.modal-footer
        button type="button" class="btn btn-secondary" data-dismiss="modal" Close
        button type="button" class="btn btn-primary" data-dismiss="modal" Upload

javascript:
  function readURL(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();

      reader.onload = function (e) {
        $('#preview').attr('src', e.target.result);
        $('#preview').css('display', 'block');
      };

      reader.readAsDataURL(input.files[0]);
    }
  }